apiVersion: tekton.dev/v1beta1 
kind: Task 
metadata: 
  name: clean-up 
spec: 
  steps: 
    - name: cleanup 
      image: ubuntu 
        rm -rf /workspace/source/* 
 
apiVersion: tekton.dev/v1beta1 
kind: Task 
metadata: 
  name: run-tests 
spec: 
  steps: 
    - name: run-tests 
      image: python:3.x 
        pip install nose 
        nosetests 
